name: speed_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_digit: ^3.2.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  graphql_flutter: ^5.1.2
  http_parser: ^4.0.2
  lottie: ^2.2.0
  provider: ^6.0.5
  rive: ^0.10.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/RiveAssets/
    - assets/LottieAssets/
