name: speed_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  speed_test_dart: ^1.0.4+1
  rive: ^0.10.2
  flutter_svg: ^2.0.2
  animated_digit: ^3.2.1
  lottie: ^2.2.0
  google_fonts: ^4.0.3
  graphql_flutter: ^5.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/RiveAssets/
    - assets/LottieAssets/
